//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPWebServis.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SETUP_CITY
    {
        public int CITY_ID { get; set; }
        public string CITY_NAME { get; set; }
        public string PHONE_CODE { get; set; }
        public string PLATE_CODE { get; set; }
        public Nullable<int> COUNTRY_ID { get; set; }
        public Nullable<System.DateTime> RECORD_DATE { get; set; }
        public Nullable<int> RECORD_EMP { get; set; }
        public string RECORD_IP { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<int> UPDATE_EMP { get; set; }
        public string UPDATE_IP { get; set; }
        public Nullable<int> PRIORITY { get; set; }
    }
}
